options:
  github-client:
    type: string
    default: ""
    description: Github OAuth client ID
  github-secret:
    type: string
    default: ""
    description: Github OAuth Secret
  channel:
    type: string
    default: "edge"
    description: Snap channel to subscribe to
